/**
 * Additional MCP Servers - November 2025 Update
 * Real servers from the MCP ecosystem
 * Sources: github.com/modelcontextprotocol/servers, github.com/wong2/awesome-mcp-servers
 */

export const newServers2025 = [
  // Official Anthropic/MCP Servers
  {
    slug: 'mcp-memory',
    name: 'MCP Memory',
    tagline: 'Knowledge graph-based persistent memory',
    description: 'Knowledge graph-based persistent memory system for AI agents. Stores and retrieves information across sessions.',
    repository_url: 'https://github.com/modelcontextprotocol/servers',
    repository_owner: 'modelcontextprotocol',
    repository_name: 'servers',
    npm_package: '@modelcontextprotocol/server-memory',
    category: 'memory',
    tags: ['memory', 'knowledge-graph', 'persistence', 'official'],
    verified: true,
    featured: true
  },
  {
    slug: 'mcp-sequential-thinking',
    name: 'Sequential Thinking',
    tagline: 'Dynamic problem-solving through thought sequences',
    description: 'Enables dynamic and reflective problem-solving through thought sequences. Allows AI to think step-by-step.',
    repository_url: 'https://github.com/modelcontextprotocol/servers',
    repository_owner: 'modelcontextprotocol',
    repository_name: 'servers',
    npm_package: '@modelcontextprotocol/server-sequentialthinking',
    category: 'development',
    tags: ['thinking', 'problem-solving', 'reasoning', 'official'],
    verified: true,
    featured: true
  },
  {
    slug: 'mcp-time',
    name: 'MCP Time',
    tagline: 'Time and timezone conversion capabilities',
    description: 'Provides time and timezone conversion capabilities. Handle time zones, conversions, and date calculations.',
    repository_url: 'https://github.com/modelcontextprotocol/servers',
    repository_owner: 'modelcontextprotocol',
    repository_name: 'servers',
    npm_package: '@modelcontextprotocol/server-time',
    category: 'development',
    tags: ['time', 'timezone', 'conversion', 'official'],
    verified: true,
    featured: false
  },
  {
    slug: 'mcp-fetch',
    name: 'MCP Fetch',
    tagline: 'Web content fetching and conversion',
    description: 'Web content fetching and conversion for efficient LLM usage. Extracts and formats web pages for AI consumption.',
    repository_url: 'https://github.com/modelcontextprotocol/servers',
    repository_owner: 'modelcontextprotocol',
    repository_name: 'servers',
    npm_package: '@modelcontextprotocol/server-fetch',
    category: 'api',
    tags: ['fetch', 'web', 'scraping', 'official'],
    verified: true,
    featured: true
  },
  {
    slug: 'mcp-git',
    name: 'MCP Git',
    tagline: 'Git repository operations',
    description: 'Tools to read, search, and manipulate Git repositories. Full Git integration for AI agents.',
    repository_url: 'https://github.com/modelcontextprotocol/servers',
    repository_owner: 'modelcontextprotocol',
    repository_name: 'servers',
    npm_package: '@modelcontextprotocol/server-git',
    category: 'development',
    tags: ['git', 'version-control', 'repository', 'official'],
    verified: true,
    featured: true
  },

  // Cloud Platforms
  {
    slug: 'aws-mcp',
    name: 'AWS MCP Server',
    tagline: 'AWS services integration',
    description: 'Comprehensive AWS services integration including CDK, documentation, and cost analysis. Manage AWS resources with AI.',
    repository_url: 'https://github.com/awslabs/mcp',
    repository_owner: 'awslabs',
    repository_name: 'mcp',
    npm_package: null,
    category: 'api',
    tags: ['aws', 'cloud', 'infrastructure'],
    verified: true,
    featured: true
  },
  {
    slug: 'azure-mcp',
    name: 'Azure MCP Server',
    tagline: 'Microsoft Azure integration',
    description: 'Access Azure Storage, Cosmos DB, and Azure CLI. Complete Azure services integration for AI agents.',
    repository_url: 'https://github.com/microsoft/mcp',
    repository_owner: 'microsoft',
    repository_name: 'mcp',
    npm_package: null,
    category: 'api',
    tags: ['azure', 'microsoft', 'cloud'],
    verified: true,
    featured: true
  },
  {
    slug: 'google-cloud-run',
    name: 'Google Cloud Run',
    tagline: 'Deployment to Google serverless',
    description: 'Deploy applications to Google Cloud Run. Manage serverless deployments with AI.',
    repository_url: 'https://github.com/googlecloudplatform/mcp-server-cloudrun',
    repository_owner: 'googlecloudplatform',
    repository_name: 'mcp-server-cloudrun',
    npm_package: null,
    category: 'api',
    tags: ['google-cloud', 'serverless', 'deployment'],
    verified: true,
    featured: false
  },
  {
    slug: 'cloudflare-mcp',
    name: 'Cloudflare MCP',
    tagline: 'CDN and edge computing',
    description: 'Manage Cloudflare resources including CDN, Workers, and edge computing. Full Cloudflare integration.',
    repository_url: 'https://github.com/cloudflare/mcp-server-cloudflare',
    repository_owner: 'cloudflare',
    repository_name: 'mcp-server-cloudflare',
    npm_package: '@cloudflare/mcp-server-cloudflare',
    category: 'api',
    tags: ['cloudflare', 'cdn', 'edge'],
    verified: true,
    featured: false
  },

  // AI & Code Execution
  {
    slug: 'e2b-mcp',
    name: 'E2B Code Sandbox',
    tagline: 'Secure code execution sandbox',
    description: 'Secure cloud sandbox for executing code. Run code safely with AI agents.',
    repository_url: 'https://github.com/e2b-dev/mcp-server',
    repository_owner: 'e2b-dev',
    repository_name: 'mcp-server',
    npm_package: '@e2b/mcp-server',
    category: 'development',
    tags: ['sandbox', 'code-execution', 'security'],
    verified: true,
    featured: true
  },
  {
    slug: 'riza-mcp',
    name: 'Riza Code Execution',
    tagline: 'Arbitrary code execution for LLMs',
    description: 'Execute arbitrary code safely for LLMs. Platform for running code from AI agents.',
    repository_url: 'https://github.com/riza-io/mcp-server',
    repository_owner: 'riza-io',
    repository_name: 'mcp-server',
    npm_package: '@riza-io/mcp-server',
    category: 'development',
    tags: ['code-execution', 'runtime', 'llm'],
    verified: true,
    featured: true
  },

  // Search & Data
  {
    slug: 'tavily-mcp',
    name: 'Tavily Search',
    tagline: 'AI-optimized search engine',
    description: 'AI-optimized search engine for comprehensive web research. Built specifically for AI agents.',
    repository_url: 'https://github.com/tavily-ai/mcp-server',
    repository_owner: 'tavily-ai',
    repository_name: 'mcp-server',
    npm_package: '@tavily/mcp-server',
    category: 'search',
    tags: ['search', 'research', 'ai-optimized'],
    verified: true,
    featured: true
  },
  {
    slug: 'exa-mcp',
    name: 'Exa Search',
    tagline: 'Search engine for AI',
    description: 'Search engine designed specifically for artificial intelligence. Semantic search capabilities.',
    repository_url: 'https://github.com/exa-labs/mcp-server',
    repository_owner: 'exa-labs',
    repository_name: 'mcp-server',
    npm_package: '@exa/mcp-server',
    category: 'search',
    tags: ['search', 'semantic', 'ai'],
    verified: true,
    featured: true
  },
  {
    slug: 'brave-search-mcp',
    name: 'Brave Search',
    tagline: 'Privacy-focused search',
    description: 'Privacy-focused web search engine. Search the web without tracking.',
    repository_url: 'https://github.com/brave/mcp-server',
    repository_owner: 'brave',
    repository_name: 'mcp-server',
    npm_package: '@brave/mcp-server',
    category: 'search',
    tags: ['search', 'privacy', 'web'],
    verified: true,
    featured: false
  },
  {
    slug: 'bright-data-mcp',
    name: 'Bright Data',
    tagline: 'Web data extraction',
    description: 'Web data discovery and extraction at scale. Comprehensive web scraping capabilities.',
    repository_url: 'https://github.com/luminati-io/mcp-server',
    repository_owner: 'luminati-io',
    repository_name: 'mcp-server',
    npm_package: null,
    category: 'api',
    tags: ['scraping', 'data-extraction', 'web-data'],
    verified: true,
    featured: false
  },
  {
    slug: 'firecrawl-mcp',
    name: 'Firecrawl',
    tagline: 'Web data extraction service',
    description: 'Advanced web data extraction and crawling service. Extract structured data from websites.',
    repository_url: 'https://github.com/mendableai/firecrawl-mcp',
    repository_owner: 'mendableai',
    repository_name: 'firecrawl-mcp',
    npm_package: '@mendable/firecrawl-mcp',
    category: 'api',
    tags: ['crawling', 'extraction', 'web'],
    verified: true,
    featured: false
  },

  // Productivity & Business
  {
    slug: 'notion-mcp',
    name: 'Notion',
    tagline: 'Workspace and document management',
    description: 'Notion workspace and document management. Create, read, and update Notion pages.',
    repository_url: 'https://github.com/makenotion/notion-mcp',
    repository_owner: 'makenotion',
    repository_name: 'notion-mcp',
    npm_package: '@notionhq/mcp-server',
    category: 'communication',
    tags: ['notion', 'documents', 'workspace'],
    verified: true,
    featured: true
  },
  {
    slug: 'stripe-mcp',
    name: 'Stripe',
    tagline: 'Payment processing integration',
    description: 'Stripe payment processing integration. Handle payments, subscriptions, and billing.',
    repository_url: 'https://github.com/stripe/stripe-mcp',
    repository_owner: 'stripe',
    repository_name: 'stripe-mcp',
    npm_package: '@stripe/mcp-server',
    category: 'api',
    tags: ['payments', 'stripe', 'billing'],
    verified: true,
    featured: true
  },
  {
    slug: 'square-mcp',
    name: 'Square',
    tagline: 'Point-of-sale and payments',
    description: 'Square point-of-sale and payment solutions. Process transactions and manage inventory.',
    repository_url: 'https://github.com/square/mcp-server',
    repository_owner: 'square',
    repository_name: 'mcp-server',
    npm_package: '@square/mcp-server',
    category: 'api',
    tags: ['payments', 'pos', 'square'],
    verified: true,
    featured: false
  },
  {
    slug: 'mailgun-mcp',
    name: 'Mailgun',
    tagline: 'Email service integration',
    description: 'Mailgun email service integration. Send transactional and marketing emails.',
    repository_url: 'https://github.com/mailgun/mcp-server',
    repository_owner: 'mailgun',
    repository_name: 'mcp-server',
    npm_package: '@mailgun/mcp-server',
    category: 'communication',
    tags: ['email', 'mailgun', 'messaging'],
    verified: true,
    featured: false
  },

  // Databases
  {
    slug: 'neon-mcp',
    name: 'Neon Postgres',
    tagline: 'Serverless Postgres',
    description: 'Neon serverless Postgres database. Scalable PostgreSQL with branching.',
    repository_url: 'https://github.com/neondatabase/mcp-server-neon',
    repository_owner: 'neondatabase',
    repository_name: 'mcp-server-neon',
    npm_package: '@neondatabase/mcp-server',
    category: 'database',
    tags: ['postgres', 'serverless', 'neon'],
    verified: true,
    featured: true
  },
  {
    slug: 'supabase-mcp',
    name: 'Supabase',
    tagline: 'PostgreSQL with authentication',
    description: 'Supabase PostgreSQL database with built-in authentication. Complete backend solution.',
    repository_url: 'https://github.com/supabase/mcp-server',
    repository_owner: 'supabase',
    repository_name: 'mcp-server',
    npm_package: '@supabase/mcp-server',
    category: 'database',
    tags: ['supabase', 'postgres', 'auth'],
    verified: true,
    featured: true
  },
  {
    slug: 'clickhouse-mcp',
    name: 'ClickHouse',
    tagline: 'Time-series data warehouse',
    description: 'ClickHouse time-series and analytical database. Fast OLAP queries.',
    repository_url: 'https://github.com/ClickHouse/mcp-server',
    repository_owner: 'ClickHouse',
    repository_name: 'mcp-server',
    npm_package: '@clickhouse/mcp-server',
    category: 'database',
    tags: ['clickhouse', 'analytics', 'time-series'],
    verified: true,
    featured: false
  },
  {
    slug: 'neo4j-mcp',
    name: 'Neo4j',
    tagline: 'Graph database with cypher',
    description: 'Neo4j graph database with cypher query support. Build knowledge graphs.',
    repository_url: 'https://github.com/neo4j/mcp-server',
    repository_owner: 'neo4j',
    repository_name: 'mcp-server',
    npm_package: '@neo4j/mcp-server',
    category: 'database',
    tags: ['neo4j', 'graph', 'cypher'],
    verified: true,
    featured: false
  },

  // Development Tools
  {
    slug: 'atlassian-mcp',
    name: 'Atlassian',
    tagline: 'Jira and Confluence integration',
    description: 'Interact with Jira and Confluence. Manage issues, projects, and documentation.',
    repository_url: 'https://github.com/atlassian/mcp-server',
    repository_owner: 'atlassian',
    repository_name: 'mcp-server',
    npm_package: '@atlassian/mcp-server',
    category: 'development',
    tags: ['jira', 'confluence', 'atlassian'],
    verified: true,
    featured: true
  },
  {
    slug: 'gitlab-mcp',
    name: 'GitLab',
    tagline: 'GitLab repository management',
    description: 'GitLab repository management and CI/CD. Complete GitLab integration.',
    repository_url: 'https://github.com/gitlab-org/mcp-server',
    repository_owner: 'gitlab-org',
    repository_name: 'mcp-server',
    npm_package: '@gitlab/mcp-server',
    category: 'development',
    tags: ['gitlab', 'git', 'cicd'],
    verified: true,
    featured: true
  },
  {
    slug: 'circleci-mcp',
    name: 'CircleCI',
    tagline: 'CI/CD build analysis',
    description: 'CI/CD build failure analysis and management. Debug failed builds with AI.',
    repository_url: 'https://github.com/circleci/mcp-server',
    repository_owner: 'circleci',
    repository_name: 'mcp-server',
    npm_package: '@circleci/mcp-server',
    category: 'development',
    tags: ['cicd', 'circleci', 'builds'],
    verified: true,
    featured: false
  },
  {
    slug: 'github-actions-mcp',
    name: 'GitHub Actions',
    tagline: 'Workflow automation',
    description: 'GitHub Actions workflow automation integration. Manage CI/CD workflows.',
    repository_url: 'https://github.com/github/actions-mcp',
    repository_owner: 'github',
    repository_name: 'actions-mcp',
    npm_package: '@github/actions-mcp',
    category: 'development',
    tags: ['github-actions', 'automation', 'workflow'],
    verified: true,
    featured: false
  },
  {
    slug: 'vercel-mcp',
    name: 'Vercel',
    tagline: 'Deployment and hosting',
    description: 'Vercel deployment and hosting management. Deploy and manage web applications.',
    repository_url: 'https://github.com/vercel/mcp-server',
    repository_owner: 'vercel',
    repository_name: 'mcp-server',
    npm_package: '@vercel/mcp-server',
    category: 'api',
    tags: ['vercel', 'deployment', 'hosting'],
    verified: true,
    featured: true
  },
  {
    slug: 'render-mcp',
    name: 'Render',
    tagline: 'Cloud platform deployment',
    description: 'Render cloud platform deployment. Deploy apps, databases, and static sites.',
    repository_url: 'https://github.com/render-com/mcp-server',
    repository_owner: 'render-com',
    repository_name: 'mcp-server',
    npm_package: '@render/mcp-server',
    category: 'api',
    tags: ['render', 'deployment', 'hosting'],
    verified: true,
    featured: false
  },

  // Specialized Tools
  {
    slug: 'browserbase-mcp',
    name: 'Browserbase',
    tagline: 'Cloud browser automation',
    description: 'Cloud browser automation service. Run browsers in the cloud for AI agents.',
    repository_url: 'https://github.com/browserbase/mcp-server',
    repository_owner: 'browserbase',
    repository_name: 'mcp-server',
    npm_package: '@browserbase/mcp-server',
    category: 'development',
    tags: ['browser', 'automation', 'cloud'],
    verified: true,
    featured: false
  },
  {
    slug: 'elevenlabs-mcp',
    name: 'ElevenLabs',
    tagline: 'Text-to-speech synthesis',
    description: 'ElevenLabs text-to-speech synthesis. Generate realistic voice audio.',
    repository_url: 'https://github.com/elevenlabs/mcp-server',
    repository_owner: 'elevenlabs',
    repository_name: 'mcp-server',
    npm_package: '@elevenlabs/mcp-server',
    category: 'api',
    tags: ['tts', 'voice', 'audio'],
    verified: true,
    featured: true
  },
  {
    slug: 'mapbox-mcp',
    name: 'Mapbox',
    tagline: 'Geospatial data and mapping',
    description: 'Mapbox geospatial data and mapping services. Maps, geocoding, and routing.',
    repository_url: 'https://github.com/mapbox/mcp-server',
    repository_owner: 'mapbox',
    repository_name: 'mcp-server',
    npm_package: '@mapbox/mcp-server',
    category: 'api',
    tags: ['maps', 'geospatial', 'location'],
    verified: true,
    featured: false
  },
  {
    slug: 'semgrep-mcp',
    name: 'Semgrep',
    tagline: 'Code security scanning',
    description: 'Semgrep code security scanning. Find bugs and security vulnerabilities.',
    repository_url: 'https://github.com/semgrep/mcp-server',
    repository_owner: 'semgrep',
    repository_name: 'mcp-server',
    npm_package: '@semgrep/mcp-server',
    category: 'development',
    tags: ['security', 'scanning', 'sast'],
    verified: true,
    featured: false
  },
  {
    slug: 'apollo-graphql-mcp',
    name: 'Apollo GraphQL',
    tagline: 'GraphQL API integration',
    description: 'Connect GraphQL APIs to AI agents. Query and mutate GraphQL endpoints.',
    repository_url: 'https://github.com/apollographql/apollo-mcp-server',
    repository_owner: 'apollographql',
    repository_name: 'apollo-mcp-server',
    npm_package: '@apollo/mcp-server',
    category: 'api',
    tags: ['graphql', 'apollo', 'api'],
    verified: true,
    featured: true
  },
  {
    slug: 'auth0-mcp',
    name: 'Auth0',
    tagline: 'Authentication management',
    description: 'Manage Auth0 tenant operations. Handle authentication and authorization.',
    repository_url: 'https://github.com/auth0/auth0-mcp-server',
    repository_owner: 'auth0',
    repository_name: 'auth0-mcp-server',
    npm_package: '@auth0/mcp-server',
    category: 'api',
    tags: ['auth', 'authentication', 'auth0'],
    verified: true,
    featured: false
  },
  {
    slug: 'apify-mcp',
    name: 'Apify',
    tagline: '6,000+ pre-built scrapers',
    description: 'Use 6,000+ pre-built cloud tools to extract data from any website. Comprehensive web automation.',
    repository_url: 'https://github.com/apify/apify-mcp-server',
    repository_owner: 'apify',
    repository_name: 'apify-mcp-server',
    npm_package: '@apify/mcp-server',
    category: 'api',
    tags: ['apify', 'scraping', 'automation'],
    verified: true,
    featured: true
  }
];

export default newServers2025;
